### ISSUE TITLE
Add styling options for markdown

### ISSUE THREAD

**Issue by DemonZito** [qlova/seed#28]
- A markdown seed can be added with markdown.New but has no styling.
- Allow developers to add their own css styling.

Example, H1 and H2 are currently rendered as this:

![image](https://user-images.githubusercontent.com/26726421/107711380-6bd45c00-6d2c-11eb-8dc2-1625d214c61e.png)

**Comment by Splizard** [comment]
This is caused because the Qlovaseed app package introduces a CSS reset that sets many styles to a default property. I did this to help ensure cross-browser consistency. However, I believe that there should be either a default set of reasonable styles for Qlovaseed apps and/or a way to recursively style seeds and their children with set.Style options.
